// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YYRA_Team_Project.Data;

namespace YYRA_Team_Project.Migrations
{
    [DbContext(typeof(YYRA_Team_ProjectContext))]
    [Migration("20200621170728_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YYRA_Team_Project.Models.Quote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Q_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Q_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Q_Gallons")
                        .HasColumnType("int");

                    b.Property<float>("Q_Price")
                        .HasColumnType("real");

                    b.Property<float>("Q_Total")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Quote");
                });
#pragma warning restore 612, 618
        }
    }
}
